plugins {
    id("groovy")
    id("io.micronaut.library") version "4.6.1"
    id("io.micronaut.aot") version "4.6.1"
    id("com.gradleup.shadow") version "8.3.11"
    id("maven-publish")
}

// TODO: Update group and version number if applicable
group = 'org.maurodata.plugins'
version = '0.0.1-SNAPSHOT'

repositories {
    mavenLocal()
    mavenCentral()

    // TODO: Uncomment this line to depend on snapshot versions of Mauro
    // maven {url = "https://mauro-repository.com/libs-snapshot-local"}
}

dependencies {
    compileOnly("io.micronaut.groovy:micronaut-runtime-groovy")
    compileOnly("info.picocli:picocli-codegen")
    compileOnly("io.micronaut:micronaut-jackson-databind")
    compileOnly("io.micronaut.security:micronaut-security-annotations")
    compileOnly("io.micronaut.security:micronaut-security-session")
    compileOnly("io.micronaut:micronaut-inject-groovy")
    compileOnly("io.micronaut.data:micronaut-data-processor")
    // runtimeOnly("org.yaml:snakeyaml")
    compileOnly("org.apache.groovy:groovy-json")

    // Change this to depend on a different version of Mauro
    compileOnly('org.maurodata:mauro-domain:0.0.2-beta')

    // to include in jar
    implementation("info.picocli:picocli")
    implementation("ch.qos.logback:logback-classic")

    // mssql
    implementation("com.microsoft.sqlserver:mssql-jdbc")

    // databricks
    implementation("io.micronaut.sql:micronaut-jdbc-hikari")
    implementation('com.databricks:databricks-jdbc:3.+')

    // oracle
    implementation('com.oracle.database.jdbc:ojdbc17:23.26.+')
    implementation('com.oracle.database.jdbc:ucp:23.26.+')

    // for build / assemble
    compileOnly("io.micronaut:micronaut-core-reactive")
    aotPlugins("io.micronaut:micronaut-core-reactive")
}

micronaut {
    runtime("netty")
    testRuntime("spock2")
    processing {
        incremental(true)
        annotations("uk.ac.ox.softeng.mauro.*", "org.maurodata.*")
    }
    aot {
        // Please review carefully the optimizations enabled below
        // Check https://micronaut-projects.github.io/micronaut-aot/latest/guide/ for more details
        optimizeServiceLoading = false
        convertYamlToJava = false
        precomputeOperations = true
        cacheEnvironment = true
        optimizeClassLoading = true
        deduceEnvironment = true
        optimizeNetty = true
    }
}

java {
    sourceCompatibility = JavaVersion.toVersion("17")
    targetCompatibility = JavaVersion.toVersion("17")
}

// Publish to the Mauro Snapshot Repository

tasks.withType(Jar).configureEach {
    archiveBaseName.set(rootProject.name)
}

plugins.withId("maven-publish") {
    publishing {
        publications {
            create("mavenJava", MavenPublication) {
                from(components["java"])
                artifactId = "${rootProject.name}"
            }
        }

        repositories {
            maven {
                name = "MauroSnapshotRepository"
                url = "https://mauro-repository.com/libs-snapshot-local"
                credentials(PasswordCredentials)
                authentication {
                    basic(BasicAuthentication)
                }
            }
        }
    }
}
